# Generated by Django 5.2 on 2025-04-25 19:38

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='telefone_responsavel',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='usuario',
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 25, 19, 38, 55, 852206, tzinfo=datetime.timezone.utc), verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_ingresso',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de ingresso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alunos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de matrícula'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do responsável'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel_telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (00) 00000-0000', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')], verbose_name='Telefone do responsável'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('transferido', 'Transferido')], default='ativo', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (00) 00000-0000', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
