# Generated by Django 5.1.6 on 2025-06-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_aluno_options_remove_aluno_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='responsavel_telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone do responsável'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
