# Generated by Django 5.2 on 2025-05-02 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_alter_aluno_options_remove_aluno_responsavel_and_more'),
        ('turmas', '0002_turmaaluno_turmaprofessor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('para_todos', models.BooleanField(default=False)),
                ('alunos', models.ManyToManyField(blank=True, related_name='comunicados', to='alunos.aluno')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to=settings.AUTH_USER_MODEL)),
                ('turmas', models.ManyToManyField(blank=True, related_name='comunicados', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
