# Generated by Django 5.2 on 2025-05-01 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_alter_aluno_options_remove_aluno_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('profissao', models.CharField(max_length=100)),
                ('local_trabalho', models.CharField(blank=True, max_length=200, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='RelacaoAlunoResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parentesco', models.CharField(choices=[('PAI', 'Pai'), ('MAE', 'Mãe'), ('AVO', 'Avô/Avó'), ('TIO', 'Tio/Tia'), ('IRMAO', 'Irmão/Irmã'), ('TUTOR', 'Tutor Legal'), ('OUTRO', 'Outro')], max_length=10)),
                ('responsavel_financeiro', models.BooleanField(default=False)),
                ('autorizado_buscar', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_responsaveis', to='alunos.aluno')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_alunos', to='responsaveis.responsavel')),
            ],
            options={
                'verbose_name': 'Relação Aluno-Responsável',
                'verbose_name_plural': 'Relações Aluno-Responsável',
                'unique_together': {('aluno', 'responsavel')},
            },
        ),
    ]
