# Generated by Django 4.2.7 on 2025-05-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsaveis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelacaoAlunoResponsavel',
            new_name='ResponsavelAluno',
        ),
    ]
