# Generated by Django 5.2 on 2025-05-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_aluno_options_remove_aluno_responsavel_and_more'),
        ('responsaveis', '0002_rename_relacao_aluno_responsavel_to_responsavel_aluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsavel',
            options={'ordering': ['nome'], 'verbose_name': 'ResponsÃ¡vel', 'verbose_name_plural': 'ResponsÃ¡veis'},
        ),
        migrations.AlterModelOptions(
            name='responsavelaluno',
            options={'verbose_name': 'VÃ\xadnculo ResponsÃ¡vel-Aluno', 'verbose_name_plural': 'VÃ\xadnculos ResponsÃ¡vel-Aluno'},
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='profissao',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='responsavelaluno',
            old_name='data_inicio',
            new_name='data_vinculo',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='local_trabalho',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='responsavelaluno',
            unique_together={('responsavel', 'aluno')},
        ),
        migrations.AddField(
            model_name='responsavel',
            name='alunos',
            field=models.ManyToManyField(through='responsaveis.ResponsavelAluno', to='alunos.aluno'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='responsavelaluno',
            name='tipo_relacao',
            field=models.CharField(choices=[('mae', 'MÃ£e'), ('pai', 'Pai'), ('avoa', 'AvÃ³'), ('avo', 'AvÃ´'), ('tia', 'Tia'), ('tio', 'Tio'), ('irma', 'IrmÃ£'), ('irmao', 'IrmÃ£o'), ('responsavel_legal', 'ResponsÃ¡vel Legal'), ('outro', 'Outro')], default='responsavel_legal', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='responsavelaluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno'),
        ),
        migrations.AlterField(
            model_name='responsavelaluno',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsaveis.responsavel'),
        ),
        migrations.RemoveField(
            model_name='responsavelaluno',
            name='autorizado_buscar',
        ),
        migrations.RemoveField(
            model_name='responsavelaluno',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='responsavelaluno',
            name='responsavel_financeiro',
        ),
        migrations.RemoveField(
            model_name='responsavelaluno',
            name='tipo_parentesco',
        ),
    ]
