# Generated by Django 5.1.6 on 2025-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsaveis', '0003_rename_relacao_to_responsavel_aluno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsavel',
            options={'ordering': ['nome'], 'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='responsavelaluno',
            options={'verbose_name': 'Vínculo Responsável-Aluno', 'verbose_name_plural': 'Vínculos Responsável-Aluno'},
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='responsavelaluno',
            name='tipo_relacao',
            field=models.CharField(choices=[('mae', 'Mãe'), ('pai', 'Pai'), ('avoa', 'Avó'), ('avo', 'Avô'), ('tia', 'Tia'), ('tio', 'Tio'), ('irma', 'Irmã'), ('irmao', 'Irmão'), ('responsavel_legal', 'Responsável Legal'), ('outro', 'Outro')], max_length=20),
        ),
    ]
