# Generated by Django 5.1.6 on 2025-06-25 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_alter_aluno_options_remove_aluno_responsavel_and_more'),
        ('notas', '0001_initial'),
        ('professores', '0002_alter_professor_turmas'),
        ('turmas', '0002_turmaaluno_turmaprofessor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('atrasado', 'Atrasado'), ('justificado', 'Justificado')], default='presente', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno', verbose_name='Aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.disciplina', verbose_name='Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professor', verbose_name='Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Registro de Frequência',
                'verbose_name_plural': 'Registros de Frequência',
                'ordering': ['-data', 'turma', 'aluno__nome'],
                'unique_together': {('aluno', 'turma', 'disciplina', 'data')},
            },
        ),
        migrations.CreateModel(
            name='JustificativaFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo da Justificativa')),
                ('documento', models.FileField(blank=True, null=True, upload_to='justificativas/', verbose_name='Documento Comprobatório')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('data_justificativa', models.DateTimeField(auto_now_add=True, verbose_name='Data da Justificativa')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas_aprovadas', to='professores.professor', verbose_name='Aprovado por')),
                ('registro_frequencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frequencia.registrofrequencia', verbose_name='Registro de Frequência')),
            ],
            options={
                'verbose_name': 'Justificativa de Falta',
                'verbose_name_plural': 'Justificativas de Faltas',
                'ordering': ['-data_justificativa'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('anual', 'Anual')], max_length=15, verbose_name='Período')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('total_aulas', models.IntegerField(default=0, verbose_name='Total de Aulas')),
                ('total_presencas', models.IntegerField(default=0, verbose_name='Total de Presenças')),
                ('total_faltas', models.IntegerField(default=0, verbose_name='Total de Faltas')),
                ('percentual_presenca', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Presença')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notas.disciplina', verbose_name='Disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Relatório de Frequência',
                'verbose_name_plural': 'Relatórios de Frequência',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
