# Generated by Django 5.2 on 2025-05-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='professores_diretos', to='turmas.turma'),
        ),
    ]
