# Generated by Django 5.1.6 on 2025-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_alter_professor_turmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
