# Generated by Django 5.1.6 on 2025-07-07 15:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_matriculas', models.DateField(verbose_name='Data de Início das Matrículas')),
                ('data_fim_matriculas', models.DateField(verbose_name='Data de Fim das Matrículas')),
                ('series_disponiveis', models.JSONField(default=list, verbose_name='Séries Disponíveis')),
                ('turnos_disponiveis', models.JSONField(default=list, verbose_name='Turnos Disponíveis')),
                ('documentos_obrigatorios', models.JSONField(default=list, verbose_name='Documentos Obrigatórios')),
                ('email_confirmacao_ativa', models.BooleanField(default=True, verbose_name='Enviar Email de Confirmação')),
                ('email_aprovacao_ativa', models.BooleanField(default=True, verbose_name='Enviar Email de Aprovação')),
                ('email_rejeicao_ativa', models.BooleanField(default=True, verbose_name='Enviar Email de Rejeição')),
                ('matricula_ativa', models.BooleanField(default=True, verbose_name='Matrículas Ativas')),
                ('max_documentos_por_matricula', models.IntegerField(default=10, verbose_name='Máximo de Documentos por Matrícula')),
                ('tamanho_max_arquivo', models.IntegerField(default=10485760, verbose_name='Tamanho Máximo de Arquivo (bytes)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Configuração de Matrícula',
                'verbose_name_plural': 'Configurações de Matrícula',
            },
        ),
        migrations.CreateModel(
            name='MatriculaOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_matricula', models.CharField(max_length=20, unique=True, verbose_name='Código da Matrícula')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('serie_desejada', models.CharField(max_length=50, verbose_name='Série Desejada')),
                ('turno_desejado', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], max_length=20, verbose_name='Turno Desejado')),
                ('escola_anterior', models.CharField(blank=True, max_length=200, null=True, verbose_name='Escola Anterior')),
                ('ano_letivo', models.IntegerField(default=2025, verbose_name='Ano Letivo')),
                ('responsavel_nome', models.CharField(max_length=200, verbose_name='Nome do Responsável')),
                ('responsavel_cpf', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF do Responsável')),
                ('responsavel_telefone', models.CharField(max_length=15, verbose_name='Telefone do Responsável')),
                ('responsavel_email', models.EmailField(max_length=254, verbose_name='E-mail do Responsável')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('motivo_rejeicao', models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('token_confirmacao', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token de Confirmação')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
            ],
            options={
                'verbose_name': 'Matrícula Online',
                'verbose_name_plural': 'Matrículas Online',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('certidao_nascimento', 'Certidão de Nascimento'), ('rg', 'RG'), ('cpf', 'CPF'), ('comprovante_residencia', 'Comprovante de Residência'), ('historico_escolar', 'Histórico Escolar'), ('declaracao_transferencia', 'Declaração de Transferência'), ('carteira_vacinacao', 'Carteira de Vacinação'), ('foto', 'Foto 3x4'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to='documentos_matricula/', verbose_name='Arquivo')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('tamanho_arquivo', models.IntegerField(verbose_name='Tamanho do Arquivo (bytes)')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='matriculas.matriculaonline')),
            ],
            options={
                'verbose_name': 'Documento da Matrícula',
                'verbose_name_plural': 'Documentos da Matrícula',
                'ordering': ['tipo', 'data_upload'],
            },
        ),
    ]
