# Generated by Django 5.2 on 2025-04-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=20)),
                ('ano_letivo', models.IntegerField()),
                ('capacidade', models.IntegerField()),
            ],
        ),
    ]
