# Generated by Django 5.2 on 2025-05-02 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_aluno_options_remove_aluno_responsavel_and_more'),
        ('professores', '0002_alter_professor_turmas'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_matriculadas', to='alunos.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_matriculados', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Matrícula de Aluno',
                'verbose_name_plural': 'Matrículas de Alunos',
                'unique_together': {('turma', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='TurmaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(blank=True, max_length=100, null=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_vinculadas', to='professores.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores_vinculados', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Professor da Turma',
                'verbose_name_plural': 'Professores das Turmas',
                'unique_together': {('turma', 'professor', 'disciplina')},
            },
        ),
    ]
